version: '3.4'

services:
  employeesdb:
    container_name: employeesdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_employees:/var/lib/postgresql/data/

  employeesearchdb:
    container_name: employeesearchdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_employees_search:/var/lib/mongodb/data/

  rabbitmq:
    container_name: rabbitmq
    hostname: employees-mq
    environment:
      - RABBITMQ_DEFAULT_USER =guest
      - RABBITMQ_DEFAULT_PASS = guest
    restart: always
    ports:
    - "5672:5672"
    - "15672:15672"

  employees.api:
    container_name: employees.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__pgDbConnection=server=employeesdb;port=5432;database=EmployeesDb;User Id=postgres; Password=postgres; Include Error Detail=true
      - MessageBroker__Host=amqp://employees-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest

    depends_on:
      - employeesdb
      - rabbitmq

    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  employeessearch.api:
    container_name: employeessearch.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__mongoDbConnection=mongodb://root:mongopw@employeesearchdb
      - MessageBroker__Host=amqp://employees-mq:5672
      - MessageBroker__UserName=guest
      - MessageBroker__Password=guest
    depends_on:
      - employeesearchdb
      - rabbitmq

    ports:
      - "6001:8080"
      - "6061:8081"

    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro


  yarpapigateway:
    container_name: yarpapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "6004:8080"
      - "6064:8081"
    depends_on:
      - employeessearch.api
      - employees.api
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
